### ISSUE TITLE
Forward otel traces to job-server

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#102]
We can use the jaeger exporter to forward otel json encoded trace data over HTTP to job-server.

e.g.

```
exporters:
  jaeger:
    endpoint: "http://localhost:14268/api/traces"
    protocol: "http"
    # The format of the payload to send. Can be "json" or "protobuf".
    # Default is "protobuf".
    format: "json"
```

Note: found via [chatGPT](https://sharegpt.com/c/4G1umvo).

This should be easy for job-server to parse and store *somewhere*.

This solves two limitations of using honeycomb:

1) we can retain this data longer than Honeycomb's two month retention period.
2) we can surface this data to users (Honeycomb API for this is behind Enterprise tier, and [can only query last 7 days](https://docs.honeycomb.io/api/query-results/#api-restrictions) anyway)
